# Default values for shovel
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Replicas are not supported 

# -- Overrides the chart's name
nameOverride: ""
# -- Overrides the chart's computed fullname
fullnameOverride: ""

global:
  # -- A list of pull secrets is used when credentials are needed to access a container registry with username and password.
  imagePullSecrets: {}
  nodeSelector: {}
  tolerations: []
  # -- Set affinity
  affinity: {}
  # -- Pod security context
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount:
    # -- Enable service account (Note: Service Account will only be automatically created if `global.serviceAccount.name` is not set)
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- Name of an already existing service account. Setting this value disables the automatic service account creation
    name: ""
  podMonitor:
    # -- Create a [PodMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md)
    create: false
  service:
    # -- Enable Service
    enabled: true
    # -- Service type, ClusterIP, LoadBalancer or ClusterIP.
    type: ClusterIP 
    # -- Service annotations
    annotations: {}

# shovel
shovel:
  # -- Name of the container
  name: shovel
  # -- Pod annotation to be added
  podAnnotations: {}
  # -- Pod labels to be added
  podLabels: {}
  image:
    repository: "nbtim/shovel"
    # -- Container pull policy
    pullPolicy: IfNotPresent
    # -- Image tag
    tag: v1.6
  containerSecurityContext:
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  # -- Static peers settings
  ports:
    # -- Dashboard port
    http: 8546
    # -- Metrics port
    metrics: 9090
  # -- Resource requests and limits
  resources:
    limits:
      cpu: 2000m
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 4Gi
  podMonitor:
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  # -- shovel config
  shovelConfig:
    # TODO: Move to configmap and select cpng service
    pg_url: postgres:///shovel
    eth_sources:
      - name: mainnet
        chain_id: 1
        url: https://ethereum-rpc.publicnode.com
    integrations:
      - name: usdc-transfer
        enabled: true
        sources:
          - name: mainnet
          - name: base
        table:
          name: usdc
          columns:
            - name: log_addr
              type: bytea
            - name: block_time
              type: numeric
            - name: from
              type: bytea
            - name: to
              type: bytea
            - name: value
              type: numeric
        block:
          - name: log_addr
            column: log_addr
            filter_op: contains
            filter_arg:
              - a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
              - 833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
        event:
          name: Transfer
          type: event
          anonymous: false
          inputs:
            - indexed: true
              name: from
              type: address
              column: from
            - indexed: true
              name: to
              type: address
              column: to
            - name: value
              type: uint256
              column: value

cloudnative-pg:
  enabled: true

shovelCnpgCluster:
  instances: 1
  storage:
    size: 1Gi
  database: shovel
  owner: shovel
  username: shovel
  password: shovel
